/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_youngpark_simplechinesechess_NativeBridge_AIBridge */

#ifndef _Included_com_youngpark_simplechinesechess_NativeBridge_AIBridge
#define _Included_com_youngpark_simplechinesechess_NativeBridge_AIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_youngpark_simplechinesechess_NativeBridge_AIBridge
 * Method:    test
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_youngpark_simplechinesechess_NativeBridge_AIBridge_test
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
